### ISSUE TITLE
Compatibility with other chips?

### ISSUE THREAD

**Issue by AndKe** [DeanCording/owonb35#4]
many Aneng , UniT devices seems to use BT4LE device  BK3432
Described here: https://mysku.me/blog/aliexpress/82493.html

Do you know/have a clue whatever this application may be able to pull data from those? (protocol may be different, but if it could just read the data stream... the rest could be done.)

**Comment by DeanCording** [comment]
Data transmission protocol is determined by the meter's software and is independent from the BT chip.  You would have to do the same packet sniffing I did to work out this protocol.

**Comment by AndKe** [comment]
@DeanCording - thank you.
